---
- name: Make dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "/home/shibegora/vector"
    - "{{ VECTOR_CONFIG }}"
    - "{{ VECTOR_DATA_DIR }}"
  tags:
    - vector

- name: Get vector tar.gz
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.42.0/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz"
    dest: "/home/shibegora/"
  tags:
    - vector

- name: Extract vector tar.gz
  ansible.builtin.unarchive:
    src: "/home/shibegora/vector-0.42.0-x86_64-unknown-linux-musl.tar.gz"
    dest: "/home/shibegora/vector"
    remote_src: true
  tags:
    - vector

- name: Copy vector bin
  ansible.builtin.copy:
    src: /home/shibegora/vector/vector-x86_64-unknown-linux-musl/bin/vector
    dest: /usr/bin/
    mode: '0755'
    remote_src: true
  tags:
    - vector

- name: Copy *.yaml file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/vector.yaml.j2"
    dest: "{{ VECTOR_CONFIG }}/vector.yaml"
    mode: '0755'
  tags:
    - vector

- name: Copy *.service file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/vector.service.j2"
    dest: /etc/systemd/system/vector.service
    mode: '0664'
  notify: Start vector service
  tags:
    - vector