---
- name: Create Vector directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ vector_install_dir }}"
    - "{{ vector_config_dir }}"
    - "{{ vector_data_dir }}"

- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}.tar.gz"
    checksum: "sha256:{{ vector_checksum }}"

- name: Extract Vector
  ansible.builtin.unarchive:
    src: "/tmp/vector-{{ vector_version }}.tar.gz"
    dest: "{{ vector_install_dir }}"
    remote_src: yes

- name: Install Vector binary
  ansible.builtin.copy:
    src: "{{ vector_install_dir }}/vector-{{ vector_version }}/bin/vector"
    dest: "/usr/local/bin/vector"
    mode: '0755'
    remote_src: yes

- name: Deploy Vector config
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "{{ vector_config_dir }}/vector.yaml"
    mode: '0644'
  notify: restart vector

- name: Deploy systemd service
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: '0644'
  notify: restart vector